export const MOTIVATIONAL_QUOTES = [
  "Mastery is not a destination, it is a continuous journey.",
  "Your future is created by what you do today, not tomorrow.",
  "Consistency is the bridge between goals and accomplishment.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "You don't have to be great to start, but you have to start to be great.",
  "Motivation gets you started. Habit is what keeps you going.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Quality is not an act, it is a habit.",
  "Small daily improvements are the key to staggering long-term results.",
  "The secret of your future is hidden in your daily routine.",
  "Don't stop until you're proud.",
  "Great things never come from comfort zones.",
  "Focus on being productive instead of busy.",
  "Your habits will determine your future.",
  "The difference between who you are and who you want to be is what you do.",
  "Action is the foundational key to all success.",
  "Do something today that your future self will thank you for.",
  "Energy and persistence conquer all things.",
  "The best way to predict your future is to create it.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Believe you can and you're halfway there.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "You miss 100% of the shots you don't take.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Start where you are. Use what you have. Do what you can.",
  "The way to get started is to quit talking and begin doing.",
  "I find that the harder I work, the more luck I seem to have.",
  "Opportunities don't happen. You create them.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Success is not final; failure is not fatal: It is the courage to continue that counts.",
  "Never give up on a dream just because of the time it will take to accomplish it.",
  "Winning isn't everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can't, you're right.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When I let go of what I am, I become what I might be.",
  "Life is what happens to you while you're busy making other plans.",
  "If you're going through hell, keep going.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "The best revenge is massive success.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no shortcuts to any place worth going.",
  "Your life does not get better by chance, it gets better by change.",
  "Don't wait. The time will never be just right.",
  "Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon 'em.",
  "If you judge people, you have no time to love them.",
  "Great things are done by a series of small things brought together.",
  "If you tell the truth, you don't have to remember anything.",
  "A journey of a thousand miles begins with a single step.",
  "Everything has beauty, but not everyone sees it.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "If you can dream it, you can do it.",
  "The best preparation for tomorrow is doing your best today.",
  "It's not whether you get knocked down, it's whether you get up.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Success is falling nine times and getting up ten.",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
  "The mind is everything. What you think you become.",
  "The only true wisdom is in knowing you know nothing.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "You have power over your mind—not outside events. Realize this, and you will find strength.",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
  "Waste no more time arguing about what a good man should be. Be one.",
  "The impediment to action advances action. What stands in the way becomes the way.",
  "If it is not right do not do it; if it is not true do not say it.",
  "The best wealth is to live content with little.",
  "Self-control is strength. Right thought is mastery. Calmness is power.",
  "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.",
  "Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too.",
  "The happiness of your life depends upon the quality of your thoughts.",
  "Our life is what our thoughts make it.",
  "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
  "Choose not to be harmed—and you won't feel harmed. Don't feel harmed—and you haven't been.",
  "External things are not the problem. It’s your assessment of them. Which you can erase right now.",
  "The soul becomes dyed with the color of its thoughts.",
  "It is not death that a man should fear, but he should fear never beginning to live.",
  "A man's worth is no greater than his ambitions.",
  "If you want to be happy, be.",
  "Excellence is not a gift, but a skill that takes practice.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The foundation of every state is the education of its youth.",
  "The high-minded man must care more for the truth than for what people think.",
  "Pleasure in the job puts perfection in the work.",
  "Knowing yourself is the beginning of all wisdom.",
  "Happiness depends upon ourselves.",
  "Patience is bitter, but its fruit is sweet.",
  "The more you know, the more you realize you don't know.",
  "Man is by nature a social animal.",
  "The aim of art is to represent not the outward appearance of things, but their inward significance.",
  "He who has overcome his fears will truly be free.",
  "To perceive is to suffer.",
  "No great mind has ever existed without a touch of madness.",
  "Courage is the first of human qualities because it is the quality which guarantees the others.",
  "Life is not a problem to be solved, but a reality to be experienced.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "A hero is someone who has given his or her life to something bigger than oneself.",
  "What is a friend? A single soul dwelling in two bodies.",
  "Whoso would be a man must be a nonconformist.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "The only person who is educated is the one who has learned how to learn and change.",
  "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
  "Educating the mind without educating the heart is no education at all.",
  "One child, one teacher, one book, one pen can change the world.",
  "Learning never exhausts the mind.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "Change is the end result of all true learning.",
  "Tell me and I forget, teach me and I may remember, involve me and I learn.",
  "Education is the most powerful weapon which you can use to change the world.",
  "Intelligence plus character—that is the goal of true education.",
  "The roots of education are bitter, but the fruit is sweet.",
  "Education is not the filling of a pail, but the lighting of a fire.",
  "You cannot open a book without learning something.",
  "Knowledge is power.",
  "An investment in knowledge pays the best interest.",
  "The mind is not a vessel to be filled, but a fire to be kindled.",
  "The expert in anything was once a beginner.",
  "Study the past if you would divine the future.",
  "Develop a passion for learning. If you do, you will never cease to grow.",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go.",
  "It is what we know already that often prevents us from learning.",
  "Genius is one percent inspiration and ninety-nine percent perspiration.",
  "Imagination is more important than knowledge.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "I have no special talent. I am only passionately curious.",
  "The only source of knowledge is experience.",
  "A person who never made a mistake never tried anything new.",
  "The important thing is not to stop questioning. Curiosity has its own reason for existing.",
  "Weakness of attitude becomes weakness of character.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "The measure of intelligence is the ability to change.",
  "Great spirits have always encountered violent opposition from mediocre minds.",
  "In the middle of difficulty lies opportunity.",
  "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
  "Peace cannot be kept by force; it can only be achieved by understanding.",
  "Imagination is everything. It is the preview of life's coming attractions.",
  "The only way to escape the corruptible effect of praise is to go on working.",
  "Everything should be made as simple as possible, but not simpler.",
  "He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.",
  "Look deep into nature, and then you will understand everything better.",
  "All religions, arts and sciences are branches of the same tree.",
  "The value of a man should be seen in what he gives and not in what he is able to receive.",
  "Setting an example is not the main means of influencing others, it is the only means.",
  "Anyone who has never made a mistake has never tried anything new.",
  "The only thing that interferes with my learning is my education.",
  "A clever person solves a problem. A wise person avoids it.",
  "Science without religion is lame, religion without science is blind.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "Reality is merely an illusion, albeit a very persistent one.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Coincidence is God's way of remaining anonymous.",
  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.",
  "Once we accept our limits, we go beyond them.",
  "Life is a preparation for the future; and the best preparation for the future is to live as if there were none.",
  "Truth is what stands the test of experience.",
  "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
  "He who has a why to live for can bear almost any how.",
  "That which does not kill us makes us stronger.",
  "He who fights with monsters should look to it that he himself does not become a monster.",
  "And those who were seen dancing were thought to be insane by those who could not hear the music.",
  "In every real man a child is hidden that wants to play.",
  "One must still have chaos in oneself to be able to give birth to a dancing star.",
  "Man is a rope stretched between the animal and the Superman—a rope over an abyss.",
  "God is dead. God remains dead. And we have killed him.",
  "The individual has always had to struggle to keep from being overwhelmed by the tribe.",
  "Without music, life would be a mistake.",
  "To live is to suffer, to survive is to find some meaning in the suffering.",
  "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.",
  "There is always some madness in love. But there is also always some reason in madness.",
  "The man of knowledge must be able not only to love his enemies but also to hate his friends.",
  "Become who you are.",
  "We often refuse to accept an idea merely because the tone of voice in which it has been expressed is unsympathetic to us.",
  "There are no facts, only interpretations.",
  "He who climbs upon the highest mountains laughs at all tragedies, real or imaginary.",
  "In large states public education will always be mediocre, for the same reason that in large kitchens the cooking is usually bad.",
  "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
  "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.",
  "A thought, even a possibility, can shatter and transform us.",
  "Whoever is a teacher through and through takes all things seriously only in relation to his students—even himself.",
  "One should die proudly when it is no longer possible to live proudly.",
  "It is my ambition to say in ten sentences what others say in a whole book.",
  "The future influences the present just as much as the past.",
  "Is man merely a mistake of God's? Or God merely a mistake of man's?",
  "All truly great thoughts are conceived while walking.",
  "Faith: not wanting to know what is true.",
  "There are more things in heaven and earth, Horatio, than are dreamt of in your philosophy.",
  "To be, or not to be, that is the question.",
  "Cowards die many times before their deaths; the valiant never taste of death but once.",
  "We know what we are, but know not what we may be.",
  "Men at some time are masters of their fates.",
  "The robbed that smiles, steals something from the thief.",
  "Give every man thy ear, but few thy voice.",
  "All the world's a stage, and all the men and women merely players.",
  "Listen to many, speak to a few.",
  "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.",
  "Expectation is the root of all heartbreak.",
  "Brevity is the soul of wit.",
  "The course of true love never did run smooth.",
  "Love all, trust a few, do wrong to none.",
  "Some are born great, some achieve greatness, and some have greatness thrust upon 'em.",
  "What's in a name? That which we call a rose by any other name would smell as sweet.",
  "Nothing can come of nothing.",
  "True hope is swift, and flies with swallow's wings.",
  "Better a witty fool than a foolish wit.",
  "Though she be but little, she is fierce.",
  "How poor are they that have not patience!",
  "Words without thoughts never to heaven go.",
  "Small cheer and great welcome makes a merry feast.",
  "Sweet are the uses of adversity.",
  "A fool thinks himself to be wise, but a wise man knows himself to be a fool.",
  "Many a true word hath been spoken in jest.",
  "The empty vessel makes the loudest sound.",
  "Modest doubt is called the beacon of the wise.",
  "Ambition should be made of sterner stuff.",
  "Boldness be my friend.",
  "Talking isn't doing. It is a kind of good deed to say well; and yet words are not deeds.",
  "Our peace shall stand as firm as rocky mountains.",
  "I would give all my fame for a pot of ale, and safety.",
  "There is nothing either good or bad, but thinking makes it so.",
  "Action is eloquence.",
  "God hath given you one face, and you make yourself another.",
  "I am one who loved not wisely but too well.",
  "Neither a borrower nor a lender be.",
  "Hell is empty and all the devils are here.",
  "The lady doth protest too much, methinks.",
  "If music be the food of love, play on.",
  "Parting is such sweet sorrow.",
  "All that glitters is not gold.",
  "Uneasy lies the head that wears a crown.",
  "Life's but a walking shadow, a poor player that struts and frets his hour upon the stage and then is heard no more.",
  "When beggars die, there are no comets seen; the heavens themselves blaze forth the death of princes.",
  "The evil that men do lives after them; the good is oft interred with their bones.",
  "Friends, Romans, countrymen, lend me your ears.",
  "Et tu, Brute?",
  "A horse! a horse! my kingdom for a horse!",
  "Off with his head!",
  "Now is the winter of our discontent.",
  "The first thing we do, let's kill all the lawyers.",
  "Cry 'Havoc,' and let slip the dogs of war.",
  "But, for my own part, it was Greek to me.",
  "Alas, poor Yorick! I knew him, Horatio.",
  "To thine own self be true.",
  "Though this be madness, yet there is method in't.",
  "To sleep: perchance to dream: ay, there's the rub.",
  "The rest is silence.",
  "Frailty, thy name is woman!",
  "A little more than kin, and less than kind.",
  "Something is rotten in the state of Denmark.",
  "Get thee to a nunnery.",
  "There is a tide in the affairs of men which, taken at the flood, leads on to fortune.",
  "Tomorrow, and tomorrow, and tomorrow.",
  "Out, damned spot! out, I say!",
  "Double, double toil and trouble; Fire burn and caldron bubble.",
  "By the pricking of my thumbs, Something wicked this way comes.",
  "Macbeth shall never vanquished be until Great Birnam Wood to high Dunsinane Hill shall come against him.",
  "I bear a charmed life.",
  "Lay on, Macduff, and damned be him that first cries, 'Hold, enough!'",
  "The quality of mercy is not strained.",
  "If you prick us, do we not bleed? if you tickle us, do we not laugh? if you poison us, do we not die? and if you wrong us, shall we not revenge?",
  "I am a Jew. Hath not a Jew eyes?",
  "The world is still deceived with ornament.",
  "The devil can cite Scripture for his purpose.",
  "Love is blind, and lovers cannot see the pretty follies that themselves commit.",
  "All that glitters is not gold; Often have you heard that told.",
  "My bounty is as boundless as the sea, My love as deep.",
  "Good night, good night! parting is such sweet sorrow.",
  "O Romeo, Romeo! wherefore art thou Romeo?",
  "A plague o' both your houses!",
  "What's in a name? that which we call a rose by any other name would smell as sweet.",
  "These violent delights have violent ends.",
  "Wisely and slow; they stumble that run fast.",
  "O, she doth teach the torches to burn bright!",
  "But, soft! what light through yonder window breaks? It is the east, and Juliet is the sun.",
  "Under the greenwood tree Who loves to lie with me.",
  "How use doth breed a habit in a man!",
  "Small habits make a big difference over time.",
  "True mastery is the result of thousands of small repetitions.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Your potential is endless. Go do what you were created to do.",
  "Every masterpiece was once just a series of deliberate strokes.",
  "You are the architect of your own habits.",
  "One year from now, you'll wish you started today.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Don't wish it were easier, wish you were better.",
  "The pain of discipline is far less than the pain of regret.",
  "Success is not a sprint, it is a marathon of consistency.",
  "Your life is the reflection of your daily habits.",
  "Focus on the process, and the results will take care of themselves.",
  "Excellence is an art won by training and habituation.",
  "You cannot change your destination overnight, but you can change your direction.",
  "Everything is hard before it is easy.",
  "Strength does not come from winning. Your struggles develop your strengths.",
  "The only person you should compete with is yourself.",
  "Progress is impossible without change.",
  "Discipline is the bridge between goals and accomplishment.",
  "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
  "You are what you do, not what you say you'll do.",
  "Habits are the compound interest of self-improvement.",
  "The best way to get things done is to simply begin.",
  "Action may not always bring happiness, but there is no happiness without action.",
  "It's not the load that breaks you, it's the way you carry it.",
  "The only way to reach the impossible is to believe it is possible.",
  "Great things take time. Be patient and stay consistent.",
  "Your mind is a garden. Your thoughts are the seeds. You can grow flowers or you can grow weeds.",
  "Success is a journey, not a destination.",
  "Don't be afraid to fail. Be afraid not to try.",
  "The results you want are on the other side of the work you're avoiding.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Don't watch the clock; do what it does. Keep going.",
  "A smooth sea never made a skilled sailor.",
  "Hard work beats talent when talent doesn't work hard.",
  "Consistency is what transforms average into excellence.",
  "The only place where success comes before work is in the dictionary.",
  "Dream big. Start small. But most importantly, start.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success is the ability to go from failure to failure without losing your enthusiasm.",
  "The way to get started is to quit talking and begin doing.",
  "I'm a great believer in luck, and I find the harder I work the more I have of it.",
  "Don't count the days, make the days count.",
  "If you want to achieve greatness stop asking for permission.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Things work out best for those who make the best of how things work out.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "The only way to do great work is to love what you do.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The best revenge is massive success.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "A person who never made a mistake never tried anything new.",
  "The only source of knowledge is experience.",
  "The mind is everything. What you think you become.",
  "Your time is limited, don't waste it living someone else's life.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever the mind can conceive and believe, it can achieve.",
  "Strive not to be a success, but rather to be of value.",
  "Life is what happens when you're busy making other plans.",
  "We become what we think about.",
  "Life is 10% what happens to me and 90% of how I react to it.",
  "The most common way people give up their power is by thinking they don't have any.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Eighty percent of success is showing up.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Winning isn't everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can't, you're right.",
  "The best revenge is massive success.",
  "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When I let go of what I am, I become what I might be.",
  "A truly successful person is one who can lay a firm foundation with the bricks others have thrown at them.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.",
  "You miss 100% of the shots you don't take.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Your time is limited, don't waste it living someone else's life.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Start where you are. Use what you have. Do what you can.",
  "The way to get started is to quit talking and begin doing.",
  "I find that the harder I work, the more luck I seem to have.",
  "Opportunities don't happen. You create them.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Success is not final; failure is not fatal: It is the courage to continue that counts.",
  "Never give up on a dream just because of the time it will take to accomplish it.",
  "Winning isn't everything, but wanting to win is.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "You can never cross the ocean until you have the courage to lose sight of the shore.",
  "Either you run the day, or the day runs you.",
  "Whether you think you can or you think you can't, you're right.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "When I let go of what I am, I become what I might be.",
  "Life is what happens to you while you're busy making other plans.",
  "If you're going through hell, keep going.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "The best revenge is massive success.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no shortcuts to any place worth going.",
  "Your life does not get better by chance, it gets better by change.",
  "Don't wait. The time will never be just right.",
  "Be not afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon 'em.",
  "If you judge people, you have no time to love them.",
  "Great things are done by a series of small things brought together.",
  "If you tell the truth, you don't have to remember anything.",
  "A journey of a thousand miles begins with a single step.",
  "Everything has beauty, but not everyone sees it.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "If you can dream it, you can do it.",
  "The best preparation for tomorrow is doing your best today.",
  "It's not whether you get knocked down, it's whether you get up.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Success is falling nine times and getting up ten.",
  "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
  "Mastery is a lifelong pursuit.",
  "Today is your masterpiece.",
  "You have achieved perfection for today.",
  "The world belongs to the disciplined.",
  "Your momentum is unstoppable.",
  "Another day of pure mastery.",
  "You are becoming who you were meant to be.",
  "Every repetition is a vote for your future self.",
  "The discipline you show today will echo in your results tomorrow.",
  "Mastery achieved. Now, rest and repeat."
];

export function getQuoteOfDay() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  return MOTIVATIONAL_QUOTES[dayOfYear % MOTIVATIONAL_QUOTES.length];
}
